#!/usr/bin/env bash

set -e
set -x 
set -u 

settings="${1:-settings.conf}"

source "$settings"
echo java-$java-scala-$scala-sbt-$sbt-img-$docker_img_version > version.txt
sed "s#JAVA_DOCKER_BASE_HERE#$java#g; s#SCALA_VERSION_HERE#$scala#g; s#SBT_VERSION_HERE#$sbt#g" Dockerfile.template > Dockerfile

echo "### Login to docker..."
docker login --username="$USERNAME" --password="$PASSWORD"

echo "### Build..."
docker build -t `cat imagename.txt`:`cat version.txt` .

echo "### Push..."
docker push  `cat imagename.txt` # account at docker.com needed to publish

echo "### Done."
